#!/bin/bash

# Check for administrator user
if [ `id -u` != 0 ]; then
	echo "Run with administrator user (sudo)"
	exit 1;
fi

APPNAME="Forever GUI"

case "$1" in
	install)
	
			echo "-- Installaton of $APPNAME has started"

		;;
	stop)
	
		;;
	restart|force-reload)

			echo "restart/force-reload"

		;;
	*)

		echo "Usage: {start|stop|status|restart|force-reload}" >&2

	;;
esac