#!/bin/bash

# Check for administrator user
# if [ `id -u` != 0 ]; then
# 	echo "Run with administrator user (sudo)"
# 	exit 1;
# fi

APPNAME="Forever GUI"
S="   "
L="$S =============================================================="
SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
declare -a SETTINGS

case "$1" in
	install)
			
			echo ""
			echo "$S Installaton of $APPNAME has started"
			echo ""
			echo "$L"
			echo ""

			# Prompt for Domain
			while true; do
				read -p "$S Specify domain (without http://): " DOMAIN

				validDomain=`echo $DOMAIN | egrep "([a-z0-9_-]+)\.([a-zA-Z\.]){2,7}"`
				
				if [ ! -z "$validDomain" ]; then
					break;
				else
					echo ""
					echo "$S Please write a valid domain"
					echo ""
				fi
			done

			# Prompt for Port
			while true; do
				read -p "$S Specify port for $DOMAIN [443]: " PORT
				
				portRegex='^[0-9]{2,5}$'
				if [[ $PORT =~ $portRegex ]]; then
					break;
				else
					PORT=443
					echo "$S Port is set to $PORT because specified port is not matching the pattern [0-9]{2,5}"
					break;
				fi
			done

			# Prompt for Username
			while true; do
				read -p "$S Specify Administrator username: " ADMIN_USER
				
				loginRegex='^[a-zA-Z0-9_-]{5,16}$'
				if [[ $ADMIN_USER =~ $loginRegex ]]; then
					break;
				else
					echo ""
					echo "$S Please use a proper username"
					echo "$S Accepted characters: [a-zA-Z0-9_-] and length between 5 and 16 symbols"
					echo ""
				fi
			done

			# Prompt for Password
			while true; do
				read -s -p "$S Specify Administrator password: " ADMIN_PASS

				validPass=`echo $ADMIN_PASS | egrep "([a-zA-Z0-9@#-_$]){6,100}" | egrep "[a-z]" | egrep "[A-Z]"`
				
				if [ ! -z "$validPass" ]; then
					echo ""
					break;
				else
					echo ""
					echo "$S Please use stronger password."
					echo "$S Required at least one lower case letter [a-z], at least one upper case [A-Z] letter."
					echo "$S Accepted characters: a-zA-Z0-9@#-_$"
					echo ""
				fi
			done
			

			echo ""
			echo "$L"
			echo ""

			echo "$S The $APPNAME will be available at url https://$DOMAIN:$PORT"
			echo "$S You can login with username $ADMIN_USER and the specified password"
			echo ""

		;;
	reconfigure)

			echo "$S Reconfiguration of $APPNAME has started"
	
		;;
	help)

			echo "Help information [TODO]"
	
		;;
	*)

		echo "Usage: {install|reconfigure|help}"

	;;
esac